module.exports = [{
    data:{
        laravel:true
    },
    output:{
        filename:'laravel_footer.blade.php',
        path:'dist'
    },
    beforeReadFile:function(content,cb){
        cb('haha')
    }
},{
    data:{
        laravel:false
    },
    output:{
        filename:'discuz_footer.blade.php',
        path:'dist'
    }
}]